task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 4
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/angelman7/PycharmProjects/D-FINE/custom_dataset/train/images
    ann_file: /home/angelman7/PycharmProjects/D-FINE/custom_dataset/train/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 8
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/angelman7/PycharmProjects/D-FINE/custom_dataset/val/images
    ann_file: /home/angelman7/PycharmProjects/D-FINE/custom_dataset/val/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 8
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
